### ISSUE TITLE
[Add joke] Kobe 問工程師

### ISSUE THREAD

**Issue by bananaappletw** [CodeTengu/jokekappa#1]
希望新增 Kobe 與工程師的對話
```
有天 Kobe 問一工程師
Kobe: 嘿，你見過凌晨四點的洛杉磯嗎？
工程師: 有啊，通常那時我還沒睡，怎麼了？
Kobe: ...沒事
```
[source](https://www.facebook.com/kobeengineer/posts/1831039153799020)

**Comment by pi314** [comment]
Hi, @bananaappletw

我把這個 joke 整理成一行了，你看這樣通順嗎？（以及笑點有保留嗎）
```
Kobe 和一名工程師的對話：「嘿，你見過凌晨四點的洛杉磯嗎？」『有啊，通常那時我還沒睡，怎麼了？』「...沒事」
```

**Comment by bananaappletw** [comment]
@pi314 有的
感謝你

**Comment by pi314** [comment]
個人是比較傾向一次 commit 多個 jokes（版本號不會跳那麼快）
但是手邊的 jokes 已經沒有庫存了，而且這個 joke 有很明確的來源（kobeengineer）

這一秒的想法是去靠北工程師上再搜集幾個品質比較好的，再和這個一起加入，不過這樣就會再晚一點喔

@vinta 你的想法如何？

**Comment by bananaappletw** [comment]
其實自己也不確定這笑話的出處
只是看過很多次
搜尋一下搜到靠北工程師

**Comment by pi314** [comment]
我第一次看到的時候也是在靠北工程師

很多 jokes 的出處其實都無法考證了XD

**Comment by pi314** [comment]
怎麼加到 `pyjokes.json` 裡面了XDDD

嘛，反正笑話有變多就好，現在也沒有確切的分類 :P

**Comment by vinta** [comment]
啊，我現在才看到這個討論
好像應該新增一個 `kobeengineer.json` 比較好喔
至於一次 commit 一個還是多個笑話都可以啦
不過增加版本號的 commit 另外拉出來會比較好
不然很容易衝突
