### ISSUE TITLE
笑話來源錯誤？

### ISSUE THREAD

**Issue by adison** [CodeTengu/JokeKappa#10]
codetengu_weekly.json的笑話中，這段
```
{
        "content": "小明在開發軟體時總是嚴格地遵循各項協定與標準，直到他看了 ISO 3166-1",
        "issue_number": 117,
        "reterence": "https://twitter.com/vinta/status/971348958831235072"
},
```
但是 [https://twitter.com/vinta/status/971348958831235072](Twitter)
的內容是：
```
「這點你不用擔心，本公司不用打卡，所以上下班時間非常彈性，喔不過我們通常會在早上七點開 Daily Scrum Meeting」
```

---
另外，有人可以解釋 ISO 3166-1 的笑點嗎...

**Comment by vinta** [comment]
@adison 感謝回報，已修正！沒想到真的有人會去看 reference 哈哈哈

你可以看一下 ISO 3166-1 裡面關於台灣的條目

**Comment by adison** [comment]
@vinta  身為臺灣人，懂
