### ISSUE TITLE
增加 jokes

### ISSUE THREAD

**Issue by pi314** [CodeTengu/jokekappa#2]
您好，

我大概在五分鐘前看到這個還非常年輕的專案，就裝了 🎉 

很久以前有送過 patch 給 pyjokes，想要貢獻中文的 jokes，但對方遲遲沒有回應，而且幾乎所有的中文 jokes 都無法通過 pyjokes 的 testing。

這裡是個人翻譯的 pyjokes 笑話：
https://github.com/pi314/pi314.notes/blob/master/jokes/programmers-jokes/from-pyjokes.rst
請問是否可以加入這個專案呢？
（若覺得有點多的話我可以整理一下發 pull request，上面的連結也不是全部的 jokes）
（註：我沒有詢問過那些 jokes 的授權，pyjokes 上似乎也沒看到出處）

謝謝

**Comment by pi314** [comment]
此外如果要加入新的中文 jokes 的話，句尾是否要加上句點呢？

**Comment by vinta** [comment]
pull request 當然好啊，如果都是有特定來源的話，應該是可以直接在 [jokekappa/jokes](https://github.com/CodeTengu/jokekappa/tree/master/jokekappa/jokes) 目錄底下新增一個 `pyjokes.json`。中文的話，句尾就不用加句號了，看起來比較有衝擊性 XD

至於註明出處的話，我也沒想到什麼好的做法，畢竟很多笑話已經流傳很久了，要考證也是有點麻煩。不過如果有些明確知道出處的，可能可以在 joke entity 裡面新增一個 `"reference": "https://xxx.com/123"` 表示一下。

**Comment by pi314** [comment]
好的，那我下班後整理一下，以中文的 jokes 為主，發一個 pull request XD

**Comment by pi314** [comment]
pull request 丟出去才想到還有別的 jokes 還沒整理，順便把 pyjokes 以外的也加進來好了

**Comment by pi314** [comment]
增加了接近 100 個 jokes，裡面可能有重覆的，或是和現有的重覆，但 sort 以後應該沒有完全一樣的兩句

**Comment by vinta** [comment]
歐爺，0.1.6 版已發佈！https://pypi.python.org/pypi/jokekappa/0.1.6

> 要怎麼知道一個人是不是 Vim 使用者？別擔心，他們會告訴你
> 服務生：「他噎到了！這裡有沒有醫生？」程式設計師：「我是 Vim 使用者。」

哈哈哈這個笑話我喜歡！
