### ISSUE TITLE
Translate them to english? 

### ISSUE THREAD

**Issue by HeyTech** [CodeTengu/jokekappa#7]
Good day!  
this seems fun, can you translate them to English? 

Best regards

**Comment by vinta** [comment]
@HeyTech There are several jokes we collect and translate are borrowed from [pyjokes](https://github.com/pyjokes/pyjokes), maybe you could just try pyjokes?

We will seriously consider multi-language support.

**Comment by HeyTech** [comment]
Thank you for you answer, i will try that :) 

Good luck!
